[tool.black]
line-length = 79
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/node_modules/
'''

[tool.isort]
profile = "black"
line_length = 79
