apiVersion: v1
kind: Secret
metadata:
  name: oauth-credentials
  namespace: ai-services
type: Opaque
stringData:
  client-id: "replace-with-actual-client-id"
  client-secret: "replace-with-actual-client-secret"
  jwt-secret: "replace-with-actual-jwt-secret"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-middleware
  namespace: ai-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-middleware
  template:
    metadata:
      labels:
        app: auth-middleware
    spec:
      containers:
      - name: auth-middleware
        image: oauth2-proxy/oauth2-proxy:latest
        args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-credentials
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-credentials
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-credentials
              key: jwt-secret
        ports:
        - containerPort: 4180
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-middleware
  namespace: ai-services
spec:
  ports:
  - port: 4180
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: auth-middleware
