apiVersion: v1
kind: Namespace
metadata:
  name: ai-services
  labels:
    name: ai-services
    security-tier: restricted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-service-binding
subjects:
- kind: ServiceAccount
  name: ai-service
  namespace: ai-services
roleRef:
  kind: ClusterRole
  name: ai-service-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service
  namespace: ai-services
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
