apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-strategy
  namespace: ai-services
data:
  strategy.yaml: |
    environments:
      staging:
        validation:
          - name: health-check
            endpoint: /health
            timeout: 30s
            interval: 5s
            threshold: 3
          - name: metrics-check
            query: rate(http_requests_total{status=~"5.."}[5m])
            threshold: 0.1
        rollback:
          automatic: true
          metrics_window: 5m
          error_threshold: 0.1
          
      production:
        promotion:
          - name: staging-validation
            duration: 30m
            success_rate: 0.99
          - name: performance-check
            latency_p95: 200ms
            error_rate: 0.01
        rollback:
          automatic: true
          metrics_window: 10m
          error_threshold: 0.05
          notify_on_rollback: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: ai-services
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: ai-service
        image: ghcr.io/nu-gui/nu-cron/ai-service:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-service-pdb
  namespace: ai-services
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ai-service
