apiVersion: install.linkerd.io/v1alpha1
kind: LinkerdConfig
metadata:
  name: linkerd-config
  namespace: linkerd
spec:
  identityTrustAnchorsPEM: "replace-with-ca-certificate"
  identity:
    issuer:
      scheme: kubernetes.io/tls
  proxyInit:
    image:
      name: cr.l5d.io/linkerd/proxy-init
      version: v1.5.3
  proxy:
    image:
      name: cr.l5d.io/linkerd/proxy
      version: stable-2.14.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    ports:
      admin:
        port: 4191
      outbound:
        port: 4140
      inbound:
        port: 4143
    waitBeforeExitSeconds: 0
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    linkerd.io/control-plane-ns: linkerd
    config.linkerd.io/admission-webhooks: disabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-controller
  namespace: linkerd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-controller
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-controller
subjects:
- kind: ServiceAccount
  name: linkerd-controller
  namespace: linkerd
