apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-lifecycle
  namespace: monitoring
data:
  lifecycle-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_age": "1d",
                "max_size": "5gb"
              }
            }
          },
          "warm": {
            "min_age": "2d",
            "actions": {
              "shrink": {
                "number_of_shards": 1
              },
              "forcemerge": {
                "max_num_segments": 1
              }
            }
          },
          "delete": {
            "min_age": "7d",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
  curator-actions.yml: |
    actions:
      1:
        action: delete_indices
        description: "Clean up old indices"
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-curator
  namespace: monitoring
spec:
  schedule: "0 1 * * *"  # Run at 1 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: elasticsearch-curator:5.8.4
            args: ["--config", "/etc/curator/config.yml", "/etc/curator/actions.yml"]
            resources:
              limits:
                cpu: "200m"
                memory: "256Mi"
              requests:
                cpu: "100m"
                memory: "128Mi"
            volumeMounts:
            - name: curator-config
              mountPath: /etc/curator
          restartPolicy: OnFailure
          volumes:
          - name: curator-config
            configMap:
              name: logstash-lifecycle
