apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-rules
  namespace: monitoring
  labels:
    app: prometheus
spec:
  groups:
  - name: node.rules
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) by (pod) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage detected
        description: Pod {{ $labels.pod }} has high CPU usage (> 80%) for more than 5 minutes

    - alert: HighMemoryUsage
      expr: sum(container_memory_usage_bytes{container!=""}) by (pod) / sum(container_spec_memory_limit_bytes{container!=""}) by (pod) > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        description: Pod {{ $labels.pod }} has high memory usage (> 85%) for more than 5 minutes

    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) * 60 * 5 > 5
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: Pod is crash looping
        description: Pod {{ $labels.pod }} is restarting frequently

  - name: prometheus.rules
    rules:
    - alert: PrometheusTargetMissing
      expr: up == 0
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: Prometheus target missing
        description: Target {{ $labels.instance }} is down

    - alert: PrometheusTooManyRestarts
      expr: changes(process_start_time_seconds{job="prometheus"}[15m]) > 2
      labels:
        severity: warning
      annotations:
        summary: Prometheus too many restarts
        description: Prometheus has restarted more than 2 times in 15 minutes

  - name: storage.rules
    rules:
    - alert: PersistentVolumeFilling
      expr: kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes * 100 < 20
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: PersistentVolume is filling up
        description: PersistentVolume {{ $labels.persistentvolume }} is {{ $value }}% full
