apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-services
  namespace: monitoring
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: backend-service
  namespaceSelector:
    matchNames:
      - default
      - monitoring
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics
  namespace: monitoring
  labels:
    app: backend-service
spec:
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
  selector:
    app: prometheus
