name: AI PR Validation

on:
  pull_request:
    branches:
      - main
      - 'devin/**'

jobs:
  validate:
    name: Validate AI-Generated Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Install dependencies
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REDIS_URL: "redis://localhost:6379/0"
          CODE_GENERATION_CACHE_TTL: "3600"
          TEST_GENERATION_CACHE_TTL: "3600"
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev python3-dev
          npm ci
          poetry install
          poetry run pip check
      
      - name: Check Code Style
        run: |
          npm run lint
          poetry run flake8
          poetry run black --check .
          poetry run isort --check-only .
      
      - name: Run Tests with Coverage
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REDIS_URL: "redis://localhost:6379/0"
          CODE_GENERATION_CACHE_TTL: "3600"
          TEST_GENERATION_CACHE_TTL: "3600"
        run: |
          npm test -- --coverage --passWithNoTests
          poetry run pytest --cov=. --cov-report=xml
      
      - name: Check Test Coverage
        uses: coverallsapp/github-action@v2
