name: AI-Managed CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'devin/**'

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.12'

jobs:
  validate:
    name: Validate Code and Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        env:
          ENV: "production"
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REDIS_URL: "redis://localhost:6379/0"
          CODE_GENERATION_CACHE_TTL: "3600"
          TEST_GENERATION_CACHE_TTL: "3600"
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev python3-dev
          npm ci
          poetry config installer.max-workers 1
          poetry lock --no-update
          PIP_ONLY_BINARY=:all: DISABLE_CYTHON=1 poetry install
          poetry run pip check
      
      - name: Run linting
        run: |
          npm run lint
          poetry run flake8
          poetry run black --check .
          poetry run isort --check-only .
      
      - name: Run security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium

  test:
    name: Run Tests
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        env:
          ENV: "production"
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REDIS_URL: "redis://localhost:6379/0"
          CODE_GENERATION_CACHE_TTL: "3600"
          TEST_GENERATION_CACHE_TTL: "3600"
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev python3-dev
          npm ci
          poetry config installer.max-workers 1
          poetry lock --no-update
          PIP_ONLY_BINARY=:all: DISABLE_CYTHON=1 poetry install
          poetry run pip check
      
      - name: Run tests
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REDIS_URL: "redis://localhost:6379/0"
          CODE_GENERATION_CACHE_TTL: "3600"
          TEST_GENERATION_CACHE_TTL: "3600"
        run: |
          npm test -- --passWithNoTests
          poetry run pytest
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage/
            pytest-results/

  build:
    name: Build and Package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-staging:
    name: Deploy to Staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up kubectl
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      
      - name: Deploy to staging
        run: |
          kubectl apply -f kubernetes/
          kubectl rollout status deployment/ai-service -n ai-services
      
      - name: Run integration tests
        run: |
          npm run test:integration
          poetry run pytest tests/integration/

  deploy-production:
    name: Deploy to Production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ai-service.example.com
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up kubectl
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_PROD }}
      
      - name: Deploy to production
        run: |
          kubectl apply -f kubernetes/
          kubectl rollout status deployment/ai-service -n ai-services
      
      - name: Verify deployment
        run: |
          curl -f https://ai-service.example.com/health
          poetry run pytest tests/smoke/
