name: AI Quality Gates

on:
  pull_request:
    branches:
      - main
      - 'devin/**'

env:
  PYTHON_VERSION: '3.11'

jobs:
  check-code-style:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run linting
        run: |
          python -m flake8 .
          python -m black --check .
          python -m isort --check-only .
